version: '4.7'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    env_file:
      - .env.local
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
